apiVersion: v1
kind: Service
metadata:
  name: mdwapp
  namespace: mdwtest
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#    service.beta.kubernetes.io/aws-load-balancer-type: external

     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
     service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#     service.beta.kubernetes.io/aws-load-balancer-type: "external
     service.beta.kubernetes.io/aws-load-balancer-scheme: internal
     service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-013a269c8657a2bdc,subnet-0177ee577a79709c8
     service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "10.0.0.20, 10.0.32.20"
     service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
     service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-086ab4696b2e13df7
     service.beta.kubernetes.io/aws-load-balancer-name: gmfs-ire-prod-nlb-mdw
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: middleware